services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5011:3000"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G

  writer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5012:3000"
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
